---

- name: "configuration play." 

  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - ansible_host_key_checking: false   # to skip the user confirmation on SSH authentication

  pre_tasks:
  - name: "wait 600 seconds for target connection to become reachable/usable."
    shell: sleep 20
  - name: "install Docker engine"
    shell: echo "test!"
      sudo apt install apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic test"
      sudo apt update
      sudo apt install -y docker-ce
      docker --version 

  roles:
  - configure-server