
---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install Docker"
  shell: | 
      sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic test"
      sudo apt update
      sudo apt install -y docker-ce
      docker --version 


 
#this step is done manually on the EC2 instance to initialize the minikube cluster
#- name: "install Kubernetes"
#  shell: | 
#      sudo curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
#      sudo install  minikube-linux-amd64 /usr/local/bin/minikube
#      sudo usermod -aG docker $USER && newgrp docker
#      minikube start --driver=docker
#      sudo snap install kubectl --classic


- name: "run Kubernetes script"
  shell: | 
      dockerpath="199420172020/capstone"
      sudo docker login -u "199420172020" -p samehmahmoudgaber	 &&\
      kubectl run mypod  --image=199420172020/capstone
      kubectl get pods
      sleep 20
      kubectl port-forward mypod 8000:80 &

    



 

