
---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install Docker(1)"
  become: True
  shell: | 
      pwd
      echo "test"
      sudo apt install apt-transport-https ca-certificates curl software-properties-common

- name: "install Docker(2)"
  become: True
  shell: | 
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic test"

- name: "install Docker(3)"
  become: True
  shell: | 
      sudo apt update
      sudo apt install -y docker-ce
      docker --version 

    



 

